# Generated by Django 3.2.4 on 2024-05-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='flan',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='flan',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flan',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
